Name : Gaddameedi Lohith
email-id : lohith.g.444@gmail.com

Assignment-1

In [2]:
import numpy as np
x = int(input())
arr = np.random.randint(0,x,(1,20)) 
print(arr)

6
[[2 1 3 0 5 4 3 2 1 2 2 3 4 4 0 5 0 0 3 1]]


Assignment-2

In [3]:
arr = np.arange(300, 500, 10).reshape(4,5)
print(arr)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


Assignment-3

In [5]:
new_arr = np.random.randint(-1000,1000,(20,20)) 
print(new_arr)
print("Maximum value = ", np.max(new_arr))
print("Minimum value = ", np.min(new_arr))
print("Mean = ", np.mean(new_arr))

[[-559 -788 -648  504 -223  403  641  374  169 -847 -912  296  590  -50
  -588  228 -611 -383  -18 -628]
 [ 930 -986 -251  925  611  666 -147  -61  623  265 -410  -59 -498 -632
   604  859 -226 -755 -213  -43]
 [-412   -5 -528  934 -279  416 -587  606  540  877  842  621  687 -529
   580  553 -977  173  226  717]
 [ 776  940 -172 -353 -383  953   -1 -816  758  208  356  191  -47  179
   252 -657  -68  981  466  137]
 [-437 -919  669   99 -331 -609  354  435  560  -99  727  921  531 -586
   113  849  588 -468 -294 -473]
 [ 649  528 -511  140 -490  877  -82 -170  746  912  588  860  413  669
   374  151  449  548  555  678]
 [ 179  257  247  460  432 -568 -607 -350  403    2  204 -248  651 -525
   707 -628 -841  756 -736  965]
 [-247 -446 -812  316  445  -50 -225 -411   72 -864 -518  226 -335  299
   228 -876 -725  559  799  852]
 [ 654  752  585 -719 -459  320 -491  -10 -880 -836  621  511 -510 -950
   -27 -427  967 -308  584   16]
 [-938  -20  692 -950 -425 -223  162 -773  136 -857  59

Assignment-4

In [11]:
arr = np.random.randint(-50,50,(5,5)) 
print (arr)
rows, columns = arr.shape
arr[rows - 1] = [-1]*columns
print("After replacing the last row with -1:")
print(arr)
for number in arr[:-(rows - 2),columns-2:]:
    number *= 2
print("Multiplying the last row by 2:")
print(arr)

[[-10  21  33 -40  -8]
 [-25 -21  22  11  46]
 [  6  15 -17 -30  22]
 [-27  18 -35  25  29]
 [ -6 -47  -5 -16  -4]]
After replacing the last row with -1:
[[-10  21  33 -40  -8]
 [-25 -21  22  11  46]
 [  6  15 -17 -30  22]
 [-27  18 -35  25  29]
 [ -1  -1  -1  -1  -1]]
Multiplying the last row by 2:
[[-10  21  33 -80 -16]
 [-25 -21  22  22  92]
 [  6  15 -17 -30  22]
 [-27  18 -35  25  29]
 [ -1  -1  -1  -1  -1]]


Assignment-5

In [9]:
arr = np.random.randint(-50,50,(5,5)) 
print (arr)
arr[arr < 0] = 0
print(arr)
arr[arr % 2 != 0] = 25
print(arr)

[[ 24 -21  49  40   8]
 [ 35 -16 -32  29  -9]
 [  6 -31  27  22  -4]
 [-31  48 -16 -29 -11]
 [-33 -50  18 -23  40]]
[[24  0 49 40  8]
 [35  0  0 29  0]
 [ 6  0 27 22  0]
 [ 0 48  0  0  0]
 [ 0  0 18  0 40]]
[[24  0 25 40  8]
 [25  0  0 25  0]
 [ 6  0 25 22  0]
 [ 0 48  0  0  0]
 [ 0  0 18  0 40]]
